export function registerCurateRoutes(app, deps) {
  const { generateCuratedSceneWithQwen, buildCuratedScene, generateGuideTtsAudio } = deps;

  app.post('/api/curate', async (req, res) => {
    try {
      const description = typeof req.body?.description === 'string' ? req.body.description.trim() : '';
      const qualityPreset = typeof req.body?.qualityPreset === 'string' ? req.body.qualityPreset.trim() : undefined;
      const layoutMode = typeof req.body?.layoutMode === 'string' ? req.body.layoutMode.trim() : undefined;

      if (!description) {
        return res.status(400).json({ error: '請提供 description 字串。' });
      }

      try {
        const qwenScene = await generateCuratedSceneWithQwen(description, { qualityPreset, layoutMode });
        if (qwenScene) {
          console.log('[curate] generated by qwen');
          return res.json({
            ...qwenScene,
            __meta: {
              provider: 'qwen',
              qualityPreset: qualityPreset || 'gallery-standard',
              layoutMode: layoutMode || 'narrative',
            },
          });
        }
      } catch (qwenErr) {
        console.warn('[curate] qwen failed, fallback to local template', qwenErr);
      }

      const scene = buildCuratedScene(description);
      console.log('[curate] generated by local fallback');
      return res.json({
        ...scene,
        __meta: { provider: 'local-fallback' },
      });
    } catch (err) {
      console.error('[curate] failed', err);
      return res.status(500).json({ error: '策展服務暫時不可用。' });
    }
  });

  app.post('/api/tts/guide', async (req, res) => {
    try {
      const title = typeof req.body?.title === 'string' ? req.body.title : '';
      const artist = typeof req.body?.artist === 'string' ? req.body.artist : '';
      const description = typeof req.body?.description === 'string' ? req.body.description : '';
      const voice = typeof req.body?.voice === 'string' ? req.body.voice : '';

      const audio = await generateGuideTtsAudio({ title, artist, description, voice });

      res.setHeader('Content-Type', 'audio/mpeg');
      res.setHeader('Cache-Control', 'no-store');
      return res.send(audio);
    } catch (err) {
      console.error('[tts] guide generation failed', err);
      return res.status(500).json({ message: '語音導覽產生失敗' });
    }
  });
}
