import {
  getUserByEmail,
  insertUser,
  getUserById,
  updateUserName,
  updateUserPasswordHash,
  deleteUserById,
  listGrowthAssetContentUrlsByOwnerId,
  insertGallery,
  listGalleriesByOwnerId,
  listPublishedGalleries,
  getGalleryById,
  getPublishedGalleryById,
  updateGalleryById,
  deleteGalleryById,
  deleteCompetitionsByHostGalleryId,
  updateGalleryShareById,
  updateGalleryPublishById,
  getGalleryByShareToken,
  insertGalleryUploadLink,
  listGalleryUploadLinksByGalleryId,
  getGalleryUploadLinkByToken,
  revokeGalleryUploadLink,
  insertExhibitComment,
  listExhibitCommentsByGalleryAndItem,
  listExhibitCommentsByGalleryOwnerId,
  getExhibitCommentById,
  deleteExhibitCommentById,
  insertGrowthChild,
  listGrowthChildrenByOwnerId,
  getGrowthChildById,
  insertGrowthExhibit,
  listGrowthExhibitsByOwnerId,
  listAllGrowthExhibitsByOwnerId,
  getGrowthExhibitById,
  updateGrowthExhibitShareById,
  getGrowthExhibitByShareToken,
  insertGrowthAsset,
  getGrowthAssetById,
  listGrowthAssetsByExhibitId,
  insertGrowthComment,
  listGrowthCommentsByExhibitId,
  insertCompetition,
  listCompetitions,
  getCompetitionById,
  listCompetitionsByCreatorId,
  updateCompetitionById,
  insertCompetitionEntry,
  listCompetitionEntriesByCompetitionId,
  listCompetitionEntriesByOwnerId,
  getCompetitionEntryByCompetitionAndGallery,
  getCompetitionEntryById,
  updateCompetitionEntryById,
  deleteCompetitionEntryById,
  insertCompetitionVote,
  countCompetitionVotesByEntryId,
  hasCompetitionVote,
} from '../db.js';
import { generateGuideTtsAudio } from '../services/ttsService.js';
import { generateAgentReply } from '../services/agentService.js';
import { summarizeFeedback, polishIntro, translateText } from '../services/aiWritingService.js';
import { generateCuratorPlan } from '../services/aiCuratorService.js';
import { generateExhibitionScene } from '../services/exhibitionSceneService.js';
import {
  createBuilderSession,
  reviewBuilderSession,
  reviseBuilderSession,
} from '../services/exhibitionBuilderAgentService.js';
import { getVisitorMemory, listVisitorMemoriesByGalleryOwnerId, upsertVisitorMemory } from '../db.js';
import { resolveGalleryAccess } from '../security/galleryAccess.js';
import {
  deleteGrowthAssetFiles,
  readGrowthAssetFile,
  saveGrowthAssetFile,
} from '../services/growthAssetService.js';

export function buildAppDependencies({
  optionalAuth,
  requireAuth,
  signToken,
  signGrowthAssetToken,
  verifyGrowthAssetToken,
  adminSecret = process.env.ADMIN_SECRET,
  rateLimiters = {},
}) {
  return {
    auth: {
      requireAuth,
      signToken,
      authLimiter: rateLimiters.authLimiter,
      getUserByEmail,
      insertUser,
      getUserById,
      updateUserName,
      updateUserPasswordHash,
      deleteUserById,
      listGrowthAssetContentUrlsByOwnerId,
      deleteGrowthAssetFiles,
    },
    gallery: {
      requireAuth,
      optionalAuth,
      resolveGalleryAccess,
      commentLimiter: rateLimiters.commentLimiter,
      getUserById,
      insertGallery,
      listGalleriesByOwnerId,
      listPublishedGalleries,
      getGalleryById,
      getPublishedGalleryById,
      updateGalleryById,
      deleteGalleryById,
      deleteCompetitionsByHostGalleryId,
      updateGalleryShareById,
      updateGalleryPublishById,
      getGalleryByShareToken,
      insertGalleryUploadLink,
      listGalleryUploadLinksByGalleryId,
      getGalleryUploadLinkByToken,
      revokeGalleryUploadLink,
      insertExhibitComment,
      listExhibitCommentsByGalleryAndItem,
      listExhibitCommentsByGalleryOwnerId,
      getExhibitCommentById,
      deleteExhibitCommentById,
      listVisitorMemoriesByGalleryOwnerId,
    },
    growth: {
      requireAuth,
      commentLimiter: rateLimiters.commentLimiter,
      uploadLimiter: rateLimiters.uploadLimiter,
      getUserById,
      insertGrowthChild,
      listGrowthChildrenByOwnerId,
      getGrowthChildById,
      insertGrowthExhibit,
      listGrowthExhibitsByOwnerId,
      listAllGrowthExhibitsByOwnerId,
      getGrowthExhibitById,
      updateGrowthExhibitShareById,
      getGrowthExhibitByShareToken,
      insertGrowthAsset,
      getGrowthAssetById,
      listGrowthAssetsByExhibitId,
      signGrowthAssetToken,
      verifyGrowthAssetToken,
      saveGrowthAssetFile,
      readGrowthAssetFile,
      insertGrowthComment,
      listGrowthCommentsByExhibitId,
    },
    competition: {
      adminSecret,
      requireAuth,
      voteLimiter: rateLimiters.voteLimiter,
      getUserById,
      getGalleryById,
      insertCompetition,
      listCompetitions,
      getCompetitionById,
      listCompetitionsByCreatorId,
      updateCompetitionById,
      updateGalleryPublishById,
      insertCompetitionEntry,
      listCompetitionEntriesByCompetitionId,
      listCompetitionEntriesByOwnerId,
      getCompetitionEntryByCompetitionAndGallery,
      getCompetitionEntryById,
      updateCompetitionEntryById,
      deleteCompetitionEntryById,
      insertCompetitionVote,
      countCompetitionVotesByEntryId,
      hasCompetitionVote,
    },
    agent: {
      requireAuth,
      agentLimiter: rateLimiters.agentLimiter,
      generateAgentReply,
    },
    aiWriting: {
      requireAuth,
      aiWritingLimiter: rateLimiters.aiWritingLimiter,
      summarizeFeedback,
      polishIntro,
      translateText,
    },
    aiCurator: {
      requireAuth,
      aiWritingLimiter: rateLimiters.aiWritingLimiter,
      generateCuratorPlan,
    },
    exhibitionScene: {
      requireAuth,
      aiWritingLimiter: rateLimiters.aiWritingLimiter,
      generateExhibitionScene,
      createBuilderSession,
      reviewBuilderSession,
      reviseBuilderSession,
    },
    visitorMemory: {
      requireAuth,
      visitorMemoryLimiter: rateLimiters.visitorMemoryLimiter,
      getVisitorMemory,
      upsertVisitorMemory,
    },
    tts: {
      requireAuth,
      ttsLimiter: rateLimiters.ttsLimiter,
      generateGuideTtsAudio,
    },
  };
}
