import {
  db,
  getUserByEmail,
  insertUser,
  getUserById,
  updateUserName,
  updateUserAvatarAppearance,
  updateUserPasswordHash,
  deleteUserAndCreateFileCleanupJobs,
  markFileCleanupJobCompleted,
  markFileCleanupJobFailed,
  listGrowthAssetContentUrlsByOwnerId,
  insertGallery,
  listGalleriesByOwnerId,
  listPublishedGalleries,
  getGalleryById,
  insertMediaAsset,
  getMediaAssetById,
  bindMediaAssetsToGallery,
  deleteMediaAssetById,
  listMediaStorageFileNamesByOwnerId,
  getPublishedGalleryById,
  updateGalleryById,
  deleteGalleryById,
  deleteCompetitionsByHostGalleryId,
  updateGalleryShareById,
  updateGalleryPublishById,
  getGalleryByShareToken,
  insertGalleryUploadLink,
  listGalleryUploadLinksByGalleryId,
  getGalleryUploadLinkByToken,
  revokeGalleryUploadLink,
  insertExhibitComment,
  listExhibitCommentsByGalleryAndItem,
  listExhibitCommentsByGalleryOwnerId,
  getExhibitCommentById,
  deleteExhibitCommentById,
  insertGrowthChild,
  listGrowthChildrenByOwnerId,
  getGrowthChildById,
  insertGrowthExhibit,
  listGrowthExhibitsByOwnerId,
  listAllGrowthExhibitsByOwnerId,
  getGrowthExhibitById,
  updateGrowthExhibitShareById,
  getGrowthExhibitByShareToken,
  insertGrowthAsset,
  getGrowthAssetById,
  listGrowthAssetsByExhibitId,
  insertGrowthComment,
  listGrowthCommentsByExhibitId,
  insertCompetition,
  listCompetitions,
  getCompetitionById,
  listCompetitionsByCreatorId,
  updateCompetitionById,
  insertCompetitionEntry,
  listCompetitionEntriesByCompetitionId,
  listCompetitionEntriesByOwnerId,
  getCompetitionEntryByCompetitionAndGallery,
  getCompetitionEntryById,
  updateCompetitionEntryById,
  deleteCompetitionEntryById,
  insertCompetitionVote,
  insertCompetitionVoteAndRefreshCount,
  countCompetitionVotesByEntryId,
  hasCompetitionVote,
  getExhibitionPassport,
  insertExhibitionPassport,
  completeExhibitionPassport,
  publishExhibitionPassport,
  getPublishedSouvenirByToken,
  listRecentPublishedSouvenirs,
} from '../db.js';
import { generateGuideTtsAudio } from '../services/ttsService.js';
import { generateAgentReply } from '../services/agentService.js';
import { summarizeFeedback, polishIntro, translateText } from '../services/aiWritingService.js';
import { generateCuratorPlan } from '../services/aiCuratorService.js';
import { generateExhibitionScene } from '../services/exhibitionSceneService.js';
import {
  createBuilderSession,
  reviewBuilderSession,
  reviseBuilderSession,
} from '../services/exhibitionBuilderAgentService.js';
import { getVisitorMemory, listVisitorMemoriesByGalleryOwnerId, upsertVisitorMemory } from '../db.js';
import { resolveGalleryAccess } from '../security/galleryAccess.js';
import { createRequireActiveUser } from '../auth/activeUser.js';
import {
  deleteGrowthAssetFiles,
  readGrowthAssetFile,
  saveGrowthAssetFile,
} from '../services/growthAssetService.js';
import { exportUserData } from '../services/userDataExportService.js';
import { deleteMediaFiles } from '../services/mediaFileService.js';
import { deleteAccountWithCleanup } from '../services/accountDeletionService.js';
import { createExhibitionPassportService } from '../services/exhibitionPassportService.js';

export function buildAppDependencies({
  optionalAuth,
  requireAuth,
  signToken,
  createCsrfToken,
  signGrowthAssetToken,
  verifyGrowthAssetToken,
  signMediaPreviewToken,
  verifyMediaPreviewToken,
  adminSecret = process.env.ADMIN_SECRET,
  rateLimiters = {},
}) {
  const requireActiveUser = createRequireActiveUser({ requireAuth, getUserById });
  const exhibitionPassportService = createExhibitionPassportService({
    getPublishedGalleryById,
    getVisitorMemory,
    getExhibitionPassport,
    insertExhibitionPassport,
    completeExhibitionPassport,
    publishExhibitionPassport,
    getPublishedSouvenirByToken,
    listRecentPublishedSouvenirs,
  });

  return {
    auth: {
      requireAuth,
      signToken,
      createCsrfToken,
      authLimiter: rateLimiters.authLimiter,
      getUserByEmail,
      insertUser,
      getUserById,
      updateUserName,
      updateUserAvatarAppearance,
      updateUserPasswordHash,
      deleteAccountWithCleanup: ({ ownerId, growthAssetUrls, mediaFileNames }) => deleteAccountWithCleanup({
        ownerId,
        growthAssetUrls,
        mediaFileNames,
        deleteUserAndCreateFileCleanupJobs,
        deleteGrowthAssetFiles,
        deleteMediaFiles,
        markFileCleanupJobCompleted,
        markFileCleanupJobFailed,
      }),
      exportUserData: (ownerId) => exportUserData(db, ownerId),
      listMediaStorageFileNamesByOwnerId,
      deleteMediaFiles,
      listGrowthAssetContentUrlsByOwnerId,
      deleteGrowthAssetFiles,
    },
    gallery: {
      requireAuth,
      optionalAuth,
      resolveGalleryAccess,
      commentLimiter: rateLimiters.commentLimiter,
      getUserById,
      insertGallery,
      listGalleriesByOwnerId,
      listPublishedGalleries,
      getGalleryById,
      getPublishedGalleryById,
      updateGalleryById,
      deleteGalleryById,
      deleteCompetitionsByHostGalleryId,
      updateGalleryShareById,
      updateGalleryPublishById,
      getGalleryByShareToken,
      insertGalleryUploadLink,
      listGalleryUploadLinksByGalleryId,
      getGalleryUploadLinkByToken,
      revokeGalleryUploadLink,
      insertExhibitComment,
      listExhibitCommentsByGalleryAndItem,
      listExhibitCommentsByGalleryOwnerId,
      getExhibitCommentById,
      deleteExhibitCommentById,
      listVisitorMemoriesByGalleryOwnerId,
    },
    growth: {
      requireAuth,
      commentLimiter: rateLimiters.commentLimiter,
      uploadLimiter: rateLimiters.uploadLimiter,
      getUserById,
      insertGrowthChild,
      listGrowthChildrenByOwnerId,
      getGrowthChildById,
      insertGrowthExhibit,
      listGrowthExhibitsByOwnerId,
      listAllGrowthExhibitsByOwnerId,
      getGrowthExhibitById,
      updateGrowthExhibitShareById,
      getGrowthExhibitByShareToken,
      insertGrowthAsset,
      getGrowthAssetById,
      listGrowthAssetsByExhibitId,
      signGrowthAssetToken,
      verifyGrowthAssetToken,
      saveGrowthAssetFile,
      readGrowthAssetFile,
      insertGrowthComment,
      listGrowthCommentsByExhibitId,
    },
    competition: {
      adminSecret,
      requireAuth,
      voteLimiter: rateLimiters.voteLimiter,
      getUserById,
      getGalleryById,
      insertCompetition,
      listCompetitions,
      getCompetitionById,
      listCompetitionsByCreatorId,
      updateCompetitionById,
      updateGalleryPublishById,
      insertCompetitionEntry,
      listCompetitionEntriesByCompetitionId,
      listCompetitionEntriesByOwnerId,
      getCompetitionEntryByCompetitionAndGallery,
      getCompetitionEntryById,
      updateCompetitionEntryById,
      deleteCompetitionEntryById,
      insertCompetitionVote,
      insertCompetitionVoteAndRefreshCount,
      countCompetitionVotesByEntryId,
      hasCompetitionVote,
    },
    agent: {
      requireActiveUser,
      agentLimiter: rateLimiters.agentLimiter,
      generateAgentReply,
    },
    aiWriting: {
      requireActiveUser,
      aiWritingLimiter: rateLimiters.aiWritingLimiter,
      summarizeFeedback,
      polishIntro,
      translateText,
    },
    aiCurator: {
      requireActiveUser,
      aiWritingLimiter: rateLimiters.aiWritingLimiter,
      generateCuratorPlan,
    },
    exhibitionScene: {
      requireActiveUser,
      aiWritingLimiter: rateLimiters.aiWritingLimiter,
      generateExhibitionScene,
      createBuilderSession,
      reviewBuilderSession,
      reviseBuilderSession,
    },
    media: {
      requireAuth: requireActiveUser,
      optionalAuth,
      uploadLimiter: rateLimiters.uploadLimiter,
      insertMediaAsset,
      getMediaAssetById,
      bindMediaAssetsToGallery,
      getGalleryById,
      getGalleryByShareToken,
      signMediaPreviewToken,
      verifyMediaPreviewToken,
      deleteMediaAssetById,
    },
    visitorMemory: {
      requireAuth,
      visitorMemoryLimiter: rateLimiters.visitorMemoryLimiter,
      getVisitorMemory,
      upsertVisitorMemory,
    },
    exhibitionPassport: {
      requireAuth,
      passportMutationLimiter: rateLimiters.passportMutationLimiter,
      souvenirReadLimiter: rateLimiters.souvenirReadLimiter,
      service: exhibitionPassportService,
    },
    tts: {
      requireActiveUser,
      ttsLimiter: rateLimiters.ttsLimiter,
      generateGuideTtsAudio,
    },
  };
}
