import { useI18n } from '@/app/components/I18nProvider';

const zhTW = {
  galleryReviewHelp: '投稿已提交或核准時，班級教師可唯讀審閱連結的私人 3D 展覽；草稿或退回修改時暫停教師存取。公開時間由作者決定。',
  title: 'AI 學習工作台', intro: '整理作品與佐證，使用 AI 反思建議，核對後提交教師評閱，再公開學習成果。',
  workspace: '班級展覽', portfolio: '我的作品集', create: '建立班級展', join: '加入班級展',
  classTitle: '展覽名稱', description: '展覽介紹', deadline: '投稿截止時間（可選）',
  invite: '學生邀請碼', inviteHelp: '只交給參展學生。加入後只能管理自己的投稿，不會取得教師權限。', copyInvite: '複製邀請碼', inviteCopied: '已複製邀請碼。', copyInviteFailed: '無法自動複製，請選取邀請碼手動複製。', copyInviteLink: '複製學生加入連結', inviteLinkCopied: '已複製學生加入連結。', inviteLinkFailed: '無法複製連結，請稍後再試。',
  joinHelp: '輸入教師提供的邀請碼。', teacher: '組展教師', student: '參展學生',
  emptyClasses: '尚未加入展覽。教師可建立班級展，學生可使用邀請碼加入。',
  loading: '載入中…', retry: '重新載入', back: '返回工作台', save: '儲存草稿', saved: '已儲存',
  working: '處理中…', draft: '草稿', submitted: '待審核', returned: '退回修改', approved: '已核准',
  titleField: '作品名稱', researchQuestion: '研究問題', concept: '創作理念', process: '創作過程',
  outcome: '成果與反思', team: '團隊成員', supervisor: '指導教師', galleryId: '連結我的 3D 展覽（可選）',
  galleryHelp: '先在「我的展覽」準備展室並於此連結，無需先公開。提交或核准後，班級教師可唯讀審閱私人展室；草稿或退回時暫停教師存取。公開時間由你決定，未連結展室仍可用文字作品集展示。',
  noGallery: '不連結 3D 展覽', submit: '提交教師審核', submitHelp: '先儲存，再提交。提交後暫停編輯，直到教師退回。',
  reopen: '建立修改版本', reopenHelp: '重新編輯後需再提交審核，已發布的文字典藏不會被覆寫。',
  feedback: '審核意見', approve: '核准作品', return: '退回修改', feedbackRequired: '退回前請填寫修改建議。',
  noProjects: '尚未收到投稿。', newProject: '準備我的投稿', projectCount: '份投稿',
  reviewTitle: '作品問答與評閱', reviewContent: '回覆內容', visibility: '可見範圍',
  private: '私人評閱（作者與教師）', public: '公開評語（下次發布時收錄）', addReview: '送出評語',
  releaseTitle: '發布與典藏', publish: '建立公開典藏', publishHelp: '只收錄已核准作品、作者名稱、團隊與指導教師資料，以及公開評語。請先確認參展者同意公開。私人評閱及未核准投稿不會公開。',
  confirmPublish: '我已確認內容與公開範圍', releaseEmpty: '尚未發布公開典藏。', viewRelease: '查看公開展覽',
  version: '版本', export: '下載作品資料', archiveNote: '這是發布當時的文字與評語定稿。作者或教師可停止公開；連結的 3D 展覽可能後續更新或停止公開。',
  withdrawRelease: '停止公開此版本', restoreRelease: '恢復公開此版本', releaseWithdrawn: '此版本已停止公開',
  noVisibleProjects: '此版本目前沒有可公開查看的作品。',
  releaseVisibilityHelp: '停止公開會停用此版本的公開連結與問答，可隨時恢復；其他版本不受影響。',
  withdrawProject: '撤下此版本中的我的作品', restoreProject: '恢復此版本中的我的作品', projectWithdrawn: '我的作品已撤下',
  projectVisibilityHelp: '只影響你在此版本中的作品與公開問答，其他人的作品會保留。其他版本及獨立 3D 展覽需分別管理。',
  releasePausedHelp: '教師已停止公開整個版本；恢復你的作品不會重新公開整個版本。',
  openGallery: '進入 3D 展覽', publicReviews: '公開評語', noPortfolio: '尚未建立畢業作品。',
  portfolioHelp: '保存創作說明與評閱狀態，下載副本作為個人留存。公開分享請使用班級典藏連結。',
  by: '作者', noDeadline: '未設定截止時間', conflict: '資料已有新版本；你的輸入仍保留。請下載草稿副本，再重新載入最新資料。',
  downloadDraft: '下載目前草稿', preview: '作品內容', required: '必填',
  workflow: '投稿 → 評閱 → 核准 → 公開典藏', roleNote: '建立者只管理這個班級展；此角色不代表平台認證教師。',
  nextReviewAction: '已提交給教師。接下來請等待評閱意見；如需修改，教師會退回作品和相關能力卡。',
};
type Copy = typeof zhTW;
const en: Copy = {
  galleryReviewHelp: 'The class organiser can review a linked private 3D gallery in read-only mode while its project is submitted or approved. Drafts and returned projects pause this access. The author decides when to publish.',
  title: 'AI learning workspace', intro: 'Organise your work and evidence, use AI reflection suggestions, check the content, and submit it for teacher review before sharing.',
  workspace: 'Class exhibitions', portfolio: 'My portfolio', create: 'Create class exhibition', join: 'Join a class',
  classTitle: 'Exhibition title', description: 'Introduction', deadline: 'Submission deadline (optional)',
  invite: 'Student invitation code', inviteHelp: 'Share only with participating students. Joining grants access to their own submission, never teacher permissions.', copyInvite: 'Copy invitation code', inviteCopied: 'Invitation code copied.', copyInviteFailed: 'Could not copy automatically. Select and copy the invitation code manually.', copyInviteLink: 'Copy student join link', inviteLinkCopied: 'Student join link copied.', inviteLinkFailed: 'Could not copy the link. Try again.',
  joinHelp: 'Enter the invitation code from your teacher.', teacher: 'Class organiser', student: 'Student',
  emptyClasses: 'No exhibitions yet. Create a class exhibition or join with an invitation code.',
  loading: 'Loading…', retry: 'Reload', back: 'Back to workspace', save: 'Save draft', saved: 'Saved',
  working: 'Working…', draft: 'Draft', submitted: 'Awaiting review', returned: 'Changes requested', approved: 'Approved',
  titleField: 'Project title', researchQuestion: 'Research question', concept: 'Creative concept', process: 'Creative process',
  outcome: 'Outcome and reflection', team: 'Team members', supervisor: 'Supervisor', galleryId: 'Link my 3D exhibition (optional)',
  galleryHelp: 'Prepare a room in My exhibitions and link it here; it can stay private. Submission or approval gives the class organiser read-only access, paused for drafts or returned projects. You decide when to publish. A text portfolio works without a room.',
  noGallery: 'No linked gallery', submit: 'Submit for review', submitHelp: 'Save before submitting. Editing pauses until the teacher returns the project.',
  reopen: 'Start a revision', reopenHelp: 'Changes require another review. Previously published text archives remain unchanged.',
  feedback: 'Review feedback', approve: 'Approve project', return: 'Request changes', feedbackRequired: 'Describe the requested changes before returning.',
  noProjects: 'No submissions yet.', newProject: 'Prepare my submission', projectCount: 'submissions',
  reviewTitle: 'Questions and feedback', reviewContent: 'Your feedback', visibility: 'Visibility',
  private: 'Private (author and teacher)', public: 'Public (included in the next release)', addReview: 'Send feedback',
  releaseTitle: 'Publish and archive', publish: 'Create public archive', publishHelp: 'Includes approved projects, author names, team and supervisor details, and public feedback. Confirm participants agree to publication. Private feedback and unapproved submissions stay private.',
  confirmPublish: 'I have checked the content and publication scope', releaseEmpty: 'No public archives yet.', viewRelease: 'View public exhibition',
  version: 'Version', export: 'Download project data', archiveNote: 'Text and feedback are frozen at publication. Authors or organisers can withdraw them. Linked 3D galleries may change or become private later.',
  withdrawRelease: 'Stop sharing this version', restoreRelease: 'Restore sharing for this version', releaseWithdrawn: 'This version is no longer public',
  noVisibleProjects: 'This version has no projects available to the public.',
  releaseVisibilityHelp: 'Stopping sharing disables this version’s public link and questions. You can restore it later; other versions are unaffected.',
  withdrawProject: 'Withdraw my project from this version', restoreProject: 'Restore my project in this version', projectWithdrawn: 'My project is withdrawn',
  projectVisibilityHelp: 'Only your project and its public questions in this version are affected. Other authors’ work stays available. Manage other versions and standalone 3D galleries separately.',
  releasePausedHelp: 'The organiser stopped sharing this entire version. Restoring your project will not make the version public.',
  openGallery: 'Open 3D exhibition', publicReviews: 'Public feedback', noPortfolio: 'No graduation projects yet.',
  portfolioHelp: 'Keep your project descriptions and review status. Download a personal copy; use class archive links for public sharing.',
  by: 'Author', noDeadline: 'No deadline', conflict: 'A newer version exists. Your input is preserved. Download a draft copy before reloading the latest data.',
  downloadDraft: 'Download current draft', preview: 'Project details', required: 'Required',
  workflow: 'Submit → Review → Approve → Archive', roleNote: 'The organiser manages this class only; this is not a verified teaching credential.',
  nextReviewAction: 'Sent to your teacher. Wait for feedback; if changes are needed, the project and related cards will be returned together.',
};
const zhCN: Copy = {
  galleryReviewHelp: '投稿已提交或核准时，班级教师可只读审阅链接的私人 3D 展览；草稿或退回修改时暂停教师访问。公开时间由作者决定。',
  title: 'AI 学习工作台', intro: '整理作品与佐证，使用 AI 反思建议，核对后提交教师评阅，再公开学习成果。',
  workspace: '班级展览', portfolio: '我的作品集', create: '建立班级展', join: '加入班级展',
  classTitle: '展览名称', description: '展览介绍', deadline: '投稿截止时间（可选）',
  invite: '学生邀请码', inviteHelp: '只交给参展学生。加入后只能管理自己的投稿，不会取得教师权限。', copyInvite: '复制邀请码', inviteCopied: '已复制邀请码。', copyInviteFailed: '无法自动复制，请选中邀请码手动复制。', copyInviteLink: '复制学生加入链接', inviteLinkCopied: '已复制学生加入链接。', inviteLinkFailed: '无法复制链接，请稍后再试。',
  joinHelp: '输入教师提供的邀请码。', teacher: '组展教师', student: '参展学生',
  emptyClasses: '尚未加入展览。教师可建立班级展，学生可使用邀请码加入。',
  loading: '载入中…', retry: '重新载入', back: '返回工作台', save: '保存草稿', saved: '已保存',
  working: '处理中…', draft: '草稿', submitted: '待审核', returned: '退回修改', approved: '已核准',
  titleField: '作品名称', researchQuestion: '研究问题', concept: '创作理念', process: '创作过程',
  outcome: '成果与反思', team: '团队成员', supervisor: '指导教师', galleryId: '链接我的 3D 展览（可选）',
  galleryHelp: '先在“我的展览”准备展室并于此链接，无需先公开。提交或核准后，班级教师可只读审阅私人展室；草稿或退回时暂停教师访问。公开时间由你决定，未链接展室仍可用文字作品集展示。',
  noGallery: '不链接 3D 展览', submit: '提交教师审核', submitHelp: '先保存，再提交。提交后暂停编辑，直到教师退回。',
  reopen: '建立修改版本', reopenHelp: '重新编辑后需再提交审核，已发布的文字典藏不会被覆盖。',
  feedback: '审核意见', approve: '核准作品', return: '退回修改', feedbackRequired: '退回前请填写修改建议。',
  noProjects: '尚未收到投稿。', newProject: '准备我的投稿', projectCount: '份投稿',
  reviewTitle: '作品问答与评阅', reviewContent: '回复内容', visibility: '可见范围',
  private: '私人评阅（作者与教师）', public: '公开评语（下次发布时收录）', addReview: '送出评语',
  releaseTitle: '发布与典藏', publish: '建立公开典藏', publishHelp: '只收录已核准作品、作者名称、团队与指导教师资料，以及公开评语。请先确认参展者同意公开。私人评阅及未核准投稿不会公开。',
  confirmPublish: '我已确认内容与公开范围', releaseEmpty: '尚未发布公开典藏。', viewRelease: '查看公开展览',
  version: '版本', export: '下载作品资料', archiveNote: '这是发布当时的文字与评语定稿。作者或教师可停止公开；链接的 3D 展览可能后续更新或停止公开。',
  withdrawRelease: '停止公开此版本', restoreRelease: '恢复公开此版本', releaseWithdrawn: '此版本已停止公开',
  noVisibleProjects: '此版本目前没有可公开查看的作品。',
  releaseVisibilityHelp: '停止公开会停用此版本的公开链接与问答，可随时恢复；其他版本不受影响。',
  withdrawProject: '撤下此版本中的我的作品', restoreProject: '恢复此版本中的我的作品', projectWithdrawn: '我的作品已撤下',
  projectVisibilityHelp: '只影响你在此版本中的作品与公开问答，其他人的作品会保留。其他版本及独立 3D 展览需分别管理。',
  releasePausedHelp: '教师已停止公开整个版本；恢复你的作品不会重新公开整个版本。',
  openGallery: '进入 3D 展览', publicReviews: '公开评语', noPortfolio: '尚未建立毕业作品。',
  portfolioHelp: '保存创作说明与评阅状态，下载副本作为个人留存。公开分享请使用班级典藏链接。',
  by: '作者', noDeadline: '未设置截止时间', conflict: '资料已有新版本；你的输入仍保留。请下载草稿副本，再重新载入最新资料。',
  downloadDraft: '下载目前草稿', preview: '作品内容', required: '必填',
  workflow: '投稿 → 评阅 → 核准 → 公开典藏', roleNote: '建立者只管理这个班级展；此角色不代表平台认证教师。',
  nextReviewAction: '已提交给教师。接下来请等待评阅意见；如需修改，教师会退回作品和相关能力卡。',
};
export function useGraduationCopy(): Copy {
  const { locale } = useI18n();
  return locale === 'en' ? en : locale === 'zh-CN' ? zhCN : zhTW;
}
