import { test, expect, request as apiRequest, type APIRequestContext, type Dialog } from '@playwright/test';

async function login(context: APIRequestContext, email: string) {
  const result = await context.post('/api/auth/login', { data: { email, password: 'SyntheticPassword2026!' } });
  expect(result.ok()).toBe(true);
  return { Authorization: `Bearer ${(await result.json()).token}` };
}

test('selected evidence, reasoned decisions and publication use the actual API and database', async ({ page, request, browser }, testInfo) => {
  const studentRequest = await apiRequest.newContext({ baseURL: 'http://127.0.0.1:5193' });
  try {
    const teacher = await login(request, 'creator@example.invalid');
    const student = await login(studentRequest, 'collaborator@example.invalid');
    const createdClass = await request.post('/api/graduation/classes', { headers: teacher, data: { title: 'Synthetic AI reflection class', description: 'Browser acceptance only' } });
    expect(createdClass.ok()).toBe(true);
    const cls = (await createdClass.json()).class;
    expect((await studentRequest.post('/api/graduation/join', { headers: student, data: { inviteToken: cls.inviteToken } })).ok()).toBe(true);
    await page.goto('/login');
    await expect(page.locator('html')).toHaveAttribute('lang', 'en');
    await page.locator('#login-email').fill('collaborator@example.invalid');
    await page.locator('#login-password').fill('SyntheticPassword2026!');
    await page.getByRole('button', { name: 'Log In', exact: true }).click();
    await expect(page).not.toHaveURL(/\/login/);
    await page.goto(`/graduation/classes/${cls.id}`);
    await page.getByLabel('Project title · Required').fill('Synthetic reflection project');
    await page.getByLabel('What question were you exploring?').fill('What did I contribute?');
    await page.getByLabel('What idea were you trying?').fill('Evidence and reflection');
    await page.getByLabel('Creative process').fill('Check a work log');
    await page.getByLabel('Outcome and reflection').fill('A schedule');
    const projectCreated = page.waitForResponse(response => response.url().endsWith(`/classes/${cls.id}/projects`) && response.request().method() === 'POST');
    await page.getByRole('button', { name: 'Save and continue', exact: true }).click();
    const project = (await (await projectCreated).json()).project;
    await page.getByLabel('Skill or experience title').fill('My event schedule');
    await page.getByLabel('Card visibility').first().selectOption('public');
    await page.getByLabel('My role').fill('Helper');
    await page.getByLabel('What I did').fill('I prepared the event schedule.');
    await page.getByLabel('What I learned').fill('I need to check outcomes.');
    await page.getByRole('button', { name: 'Add source', exact: true }).click();
    await page.getByLabel('Evidence label').nth(0).fill('Public work log');
    await page.getByLabel('Source name').nth(0).fill('Synthetic log');
    await page.getByLabel('Evidence text').fill('I prepared the event schedule.');
    await page.getByLabel('Card visibility').nth(1).selectOption('public');
    await page.getByRole('button', { name: 'Add source', exact: true }).click();
    await page.getByLabel('Evidence label').nth(1).fill('Private diary');
    await page.getByLabel('Source name').nth(1).fill('Synthetic diary');
    await page.getByLabel('Evidence text').nth(1).fill('PRIVATE_SENTINEL_NEVER_SEND');
    await page.getByLabel('Card visibility').nth(2).selectOption('private');
    await page.getByRole('button', { name: 'Add source', exact: true }).click();
    await page.getByLabel('Evidence label').nth(2).fill('Unread link');
    await page.getByLabel('Source name').nth(2).fill('Synthetic link');
    await page.getByLabel('Type').last().selectOption('link');
    await page.getByLabel('Evidence URL').fill('https://example.invalid/record?token=DO_NOT_SEND');
    await page.getByLabel('Card visibility').nth(3).selectOption('public');
    const cardCreated = page.waitForResponse(response => response.url().endsWith(`/projects/${project.id}/skills`) && response.request().method() === 'POST');
    await page.getByRole('button', { name: 'Save card', exact: true }).click();
    const card = (await (await cardCreated).json()).skill;
    const publicLog = card.evidence.find((source: { label: string }) => source.label === 'Public work log');
    const linkSource = card.evidence.find((source: { label: string }) => source.label === 'Unread link');
    const selectedSource = page.getByRole('checkbox', { name: 'Include this source in the AI request: Public work log', exact: true });
    const privateSource = page.getByRole('checkbox', { name: 'Include this source in the AI request: Private diary', exact: true });
    await expect(selectedSource).not.toBeChecked();
    await expect(privateSource).not.toBeChecked();
    await selectedSource.check();
    await page.getByRole('checkbox', { name: 'Include this source in the AI request: Unread link', exact: true }).check();
    await expect(page.getByText('Link only — URL not sent; page not opened or read')).toBeVisible();
    await page.getByRole('region', { name: 'Review what will be sent' }).screenshot({ path: testInfo.outputPath('evidence-preview.png') });
    await page.getByRole('button', { name: 'Ask AI for evidence-based suggestions' }).click();
    await expect(page.getByText('Evidence-based planning', { exact: true })).toBeVisible();
    const payloads = await (await request.get('/__test/skill-ai')).json();
    expect(payloads.at(-1).evidence.map((item: { id: string }) => item.id)).toEqual([publicLog.id, linkSource.id]);
    expect(JSON.stringify(payloads)).not.toContain('PRIVATE_SENTINEL');
    expect(JSON.stringify(payloads)).not.toContain('DO_NOT_SEND');
    await page.getByRole('button', { name: 'Use this draft', exact: true }).first().click();
    const save = page.getByRole('button', { name: 'Save card', exact: true });
    await expect(save).toBeDisabled();
    await page.getByLabel('Why did you make this decision?').fill('The work log supports preparing the schedule, but not leading the school.');
    await page.getByRole('checkbox', { name: /Public work log.*I checked this source/ }).check();
    await save.click();
    await expect(page.getByText('AI decision recorded.')).toBeVisible();
    await page.getByRole('button', { name: 'AI suggestion history', exact: true }).click();
    await expect(page.getByText(/The work log supports preparing the schedule/)).toBeVisible();
    const historyResponse = await studentRequest.get(`/api/graduation/skills/${card.id}/suggestions`, { headers: student });
    expect(historyResponse.ok()).toBe(true);
    const history = await historyResponse.json();
    expect(JSON.stringify(history)).not.toContain('PRIVATE_SENTINEL');
    const recorded = history.runs[0].suggestions.find((item: { decision: string }) => item.decision === 'adopted');
    expect(recorded.reason).toContain('work log supports');
    expect(recorded.checkedEvidenceIds).toEqual([publicLog.id]);
    await page.getByRole('button', { name: 'Continue to preview', exact: true }).click();
    await expect(page.getByRole('heading', { name: '3. Preview and submit', exact: true })).toBeVisible();
    const combinedSubmit = page.waitForResponse(response => response.url().endsWith(`/projects/${project.id}/submit-with-skills`) && response.request().method() === 'POST');
    await page.getByRole('button', { name: 'Submit to teacher', exact: true }).click();
    expect((await combinedSubmit).ok()).toBe(true);
    const cards = await (await studentRequest.get(`/api/graduation/projects/${project.id}/skills`, { headers: student })).json();
    const current = cards.skills.find((item: { id: string }) => item.id === card.id);
    expect(current.status).toBe('submitted');
    const teacherContext = await browser.newContext();
    let token: string;
    try {
      const teacherPage = await teacherContext.newPage();
      await teacherPage.goto('http://127.0.0.1:5193/login');
      await expect(teacherPage.locator('html')).toHaveAttribute('lang', 'en');
      await teacherPage.locator('#login-email').fill('creator@example.invalid');
      await teacherPage.locator('#login-password').fill('SyntheticPassword2026!');
      await teacherPage.getByRole('button', { name: 'Log In', exact: true }).click();
      await expect(teacherPage).not.toHaveURL(/\/login/);
      await teacherPage.goto(`http://127.0.0.1:5193/graduation/classes/${cls.id}`);
      await teacherPage.getByLabel('Review feedback', { exact: true }).fill('Reviewed synthetic project for browser acceptance.');
      const projectReview = teacherPage.waitForResponse(response => response.url().endsWith(`/projects/${project.id}/review-with-skills`) && response.request().method() === 'POST');
      await teacherPage.getByRole('button', { name: 'Approve project', exact: true }).click();
      expect((await projectReview).ok()).toBe(true);
      const teacherCards = await (await studentRequest.get(`/api/graduation/projects/${project.id}/skills`, { headers: student })).json();
      expect(teacherCards.skills.find((item: { id: string }) => item.id === card.id).status).toBe('approved');
      await expect(teacherPage.getByRole('button', { name: 'Approve project', exact: true })).toHaveCount(0);
      const curation = teacherPage.getByRole('region', { name: 'Exhibition grouping', exact: true });
      const workspaceLink = teacherPage.getByRole('navigation', { name: 'Graduation studio', exact: true }).getByRole('link', { name: 'Class exhibitions', exact: true });
      await curation.getByRole('button', { name: 'Suggest groups', exact: true }).click();
      const groupTitle = curation.getByLabel('Group title 1', { exact: true });
      await groupTitle.fill('Unsaved browser curation');
      await expect(curation).toHaveAttribute('aria-busy', 'false');
      const cancelledLeave = teacherPage.waitForEvent('dialog');
      const attemptedLeave = workspaceLink.click();
      const cancelDialog = await cancelledLeave;
      await cancelDialog.dismiss();
      await attemptedLeave;
      expect(cancelDialog.type()).toBe('confirm');
      expect(cancelDialog.message()).toContain('unsaved changes');
      await expect(teacherPage).toHaveURL(new RegExp(`/graduation/classes/${cls.id}$`));
      await expect(groupTitle).toHaveValue('Unsaved browser curation');
      await expect(curation).toContainText('Unsaved changes — publication uses the last confirmed plan.');

      const confirmedLeave = teacherPage.waitForEvent('dialog');
      const discardedNavigation = workspaceLink.click();
      const discardDialog = await confirmedLeave;
      await discardDialog.accept();
      await discardedNavigation;
      expect(discardDialog.type()).toBe('confirm');
      await expect(teacherPage).toHaveURL(/\/graduation$/);
      const discardedPlan = await request.get(`/api/graduation/classes/${cls.id}/curation`, { headers: teacher });
      expect(discardedPlan.ok()).toBe(true);
      expect((await discardedPlan.json()).plan).toBeNull();
      await teacherPage.locator(`a[href="/graduation/classes/${cls.id}"]`).click();
      await expect(curation.getByRole('button', { name: 'Suggest groups', exact: true })).toBeEnabled();
      await expect(groupTitle).toHaveCount(0);
      await curation.getByRole('button', { name: 'Suggest groups', exact: true }).click();
      await groupTitle.fill('Confirmed browser curation');
      await curation.getByRole('checkbox', { name: 'I reviewed the grouping and explanations.', exact: true }).check();
      const curationSaved = teacherPage.waitForResponse(response => response.url().endsWith(`/classes/${cls.id}/curation`) && response.request().method() === 'PUT');
      await curation.getByRole('button', { name: 'Confirm and save groups', exact: true }).click();
      const savedResponse = await curationSaved;
      expect(savedResponse.ok()).toBe(true);
      const savedPlan = (await savedResponse.json()).plan;
      expect(savedPlan.groups[0].title).toBe('Confirmed browser curation');
      expect(savedPlan.revision).toBe(1);
      await expect(curation).toContainText('Confirmed plan saved.');
      await expect(curation).toHaveAttribute('aria-busy', 'false');
      const savedNavigationDialogs: string[] = [];
      const rejectUnexpectedDialog = async (dialog: Dialog) => {
        savedNavigationDialogs.push(dialog.message());
        await dialog.dismiss();
      };
      teacherPage.on('dialog', rejectUnexpectedDialog);
      try {
        await workspaceLink.click();
        await expect(teacherPage).toHaveURL(/\/graduation$/);
        expect(savedNavigationDialogs).toEqual([]);
      } finally { teacherPage.off('dialog', rejectUnexpectedDialog); }
      await teacherPage.locator(`a[href="/graduation/classes/${cls.id}"]`).click();
      await expect(groupTitle).toHaveValue('Confirmed browser curation');
      await expect(curation).toContainText('Confirmed plan saved.');
      await expect(curation).toHaveAttribute('aria-busy', 'false');
      await teacherPage.getByRole('checkbox', { name: 'I have checked the content and publication scope' }).check();
      const published = teacherPage.waitForResponse(response => response.url().endsWith(`/classes/${cls.id}/publish`) && response.request().method() === 'POST');
      await teacherPage.getByRole('button', { name: 'Create public archive', exact: true }).click();
      const release = await published;
      expect(release.ok()).toBe(true);
      token = (await release.json()).release.token;
      await expect(teacherPage.getByRole('link', { name: 'View public exhibition', exact: true })).toBeVisible();
      await teacherPage.screenshot({ path: testInfo.outputPath('english-teacher-review.png'), fullPage: true });
    } finally { await teacherContext.close(); }
    await page.goto(`/graduation/public/${token}`);
    await expect(page.getByRole('heading', { name: 'Evidence-based planning' })).toBeVisible();
    await expect(page.getByText('Private diary')).toHaveCount(0);
    await expect(page.getByText(/The work log supports preparing the schedule/)).toHaveCount(0);
    const publicResult = await request.get(`/api/graduation/public/${token}`);
    const publicText = await publicResult.text();
    expect(publicText).not.toContain('PRIVATE_SENTINEL');
    expect(publicText).not.toContain('decisionReason');
    await page.screenshot({ path: testInfo.outputPath('approved-public-portfolio.png'), fullPage: true });
    await testInfo.attach('scope', { body: 'Real local API and SQLite; deterministic synthetic model provider, not evidence of real-model or educational effectiveness.', contentType: 'text/plain' });
  } finally { await studentRequest.dispose(); }
});

test('English competition orientation preserves the saved locale on a narrow screen without bypassing login', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.addInitScript(() => {
    if (location.origin === 'http://127.0.0.1:5193') localStorage.setItem('metaexpo-locale', 'zh-TW');
  });
  await page.goto('/competition-demo');
  await expect(page.getByRole('heading', { name: 'MetaEXB Learn', exact: true })).toBeVisible();
  await expect(page.locator('main[lang]')).toHaveAttribute('lang', 'en');
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-TW');
  await expect.poll(() => page.evaluate(() => localStorage.getItem('metaexpo-locale'))).toBe('zh-TW');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('competition-mobile.png'), fullPage: true });
  await page.getByRole('link', { name: 'Open student workspace' }).click();
  await expect(page).toHaveURL(/\/login/);
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-TW');
  expect(await page.evaluate(() => localStorage.getItem('metaexpo-locale'))).toBe('zh-TW');
});
